version: '3.8'

services:
  ros2_dev:
    build: .
    container_name: ros2_dev_container
    network_mode: "host"
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - .:/ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    tty: true
    stdin_open: true
