services:
  ros2_dev:
    build: .
    container_name: ros2_dev_container
    network_mode: "host"
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - .:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw 
    environment:
      - DISPLAY=${DISPLAY}
      - MESA_GL_VERSION_OVERRIDE=3.3
      - ROS_DOMAIN_ID=0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
    tty: true
    stdin_open: true

