amcl:
  ros__parameters:
    use_map_topic: true
    scan_topic: scan
    odom_topic: odom
    base_frame_id: base_link
    map_frame_id: map
    global_frame_id: map
    update_min_d: 0.2
    update_min_a: 0.2

map_server:
  ros__parameters:
    yaml_filename: ""  # nie podajesz, jeśli korzystasz z mapy z SLAM
    use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"

local_costmap:
  ros__parameters:
    footprint: "[[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]"
    resolution: 0.05
    robot_base_frame: base_link
    map_topic: map
    use_sim_time: false

global_costmap:
  ros__parameters:
    footprint: "[[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]"
    resolution: 0.05
    robot_base_frame: base_link
    map_topic: map
    use_sim_time: false
