slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: "mapping"
    always_reset_initial_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    map_update_interval: 1.0

    # WYŁĄCZ użycie odometrii:
    odom_frame: "base_link"
    map_frame: "map"
    base_frame: "base_link"
    publish_tf_map: true

    # Nie próbuj słuchać odometrii:
    use_odometry: false
    use_pose_topic: false
    use_scan_matching: true

    resolution: 0.05
    map_publish_period: 1.0
    map_update_interval: 1.0
